import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Context from "./context/Context";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Muscle Tap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased sm:overflow-hidden`}
      >
        <Context>
          <Providers>{children}</Providers>
        </Context>
      </body>
    </html>
  );
}
